# Generated by Django 5.1.6 on 2025-05-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_imagen'),
        ('core', '0003_profile_ciudad_profile_municipio_profile_pais'),
    ]

    operations = [
    ]
